#!/usr/bin/perl

=head1 NAME

bacon - OpenCL frontend, providing a better array compute notation

=head1 SYNOPSIS

bacon [OPTION]... [FILE]

=head1 DESCRIPTION

Generate OpenCL and C++ code from FILE. 

=over

=item -h

Show this documentation.

=back

=cut

use warnings FATAL => 'all';
use strict;

use 5.10.0;

use Getopt::Std qw(getopts);
use Data::Dumper;
$Data::Dumper::Terse = 1;

use Bacon::Parser;
use Bacon::Generate;

my %opts;
getopts('h', \%opts);

if (defined $opts{h}) {
    system(qq{perldoc "$0"});
    exit(0);
}

my $source = shift;
my $ast = bacon_parse($source);
bacon_generate($ast, $source);


